# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-03 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='number_in_thread',
            field=models.IntegerField(default=0),
        ),
    ]
