# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-03 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20180803_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='thread',
            new_name='threads',
        ),
        migrations.AddField(
            model_name='thread',
            name='sections',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='threads.Section'),
        ),
    ]
