# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-04 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20180804_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
