# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-04 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_thread_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='picture',
            new_name='image',
        ),
    ]
