# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-05 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_auto_20180804_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(null=True, upload_to='threads/static/threads'),
        ),
    ]
