# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-05 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_auto_20180805_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='number_of_threads_and_messages',
            field=models.IntegerField(default=0),
        ),
    ]
