# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-05 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0008_section_number_of_threads_and_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='id_threads_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='id_threads_messages',
            field=models.IntegerField(default=0),
        ),
    ]
