# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-05 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0009_auto_20180805_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to='threads/static/threads'),
        ),
    ]
