# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-05 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0010_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='number_in_thread',
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='threads/static/threads'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='threads/static/threads'),
        ),
    ]
