# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-06 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0011_auto_20180805_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='threads/static/threads/images'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='threads/static/threads/images'),
        ),
    ]
