# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-06 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0012_auto_20180806_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='threads/static/threads/videos'),
        ),
    ]
