# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-07 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0014_message_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_message_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 7, 11, 40, 52, 284644, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
